version: '3.5'

services:
    evolution.evo2build:
        environment:
            - COMPOSE_PROJECT_NAME=evolution
        build:
            context: .
            dockerfile: evo2build.Dockerfile
        image: evolution/evo2build:${TAG:-R3.0.1}
        networks:
        - evo2_network

    evolution.document.mongosync:
      build:
        context: .
        dockerfile: Windows.Evolution.Document.MongoSync.Dockerfile
      image: evolution_igoqa/document.mongosync:${TAG:-R3.0.1} 
      networks:
        - evo2_network
      deploy:
        restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 3
            window: 120s 

networks:
    evo2_network:
        external: true

volumes:
    named_vol:
