import { getlocalizeData } from '../../../../utils/commonUtils';
const localConstant = getlocalizeData();

export const HeaderData = {
    "columnDefs": [
        {
            "headerName": localConstant.gridHeader.COMPANY,
            "headerTooltip": localConstant.gridHeader.COMPANY,
            "field": "companyName",
            "filter": "agTextColumnFilter",
            "tooltipField": "companyName",
            "width": 200,
            "pinned": 'left'
        },
        {
            "headerName": localConstant.gridHeader.SUB_DIVISION,
            "headerTooltip": localConstant.gridHeader.SUB_DIVISION,
            "field": "subDivision",
            "filter": "agTextColumnFilter",
            "tooltipField": "subDivision",
            "width": 200,
            "pinned": 'left'
        },
        {
            "headerName": localConstant.gridHeader.FULL_NAME,
            "headerTooltip": localConstant.gridHeader.FULL_NAME,
            "field": "resourceName",
            "filter": "agTextColumnFilter",
            "tooltipField": "resourceName",
            "width": 200,
            "pinned": 'left'
        },
        {
            "headerName": localConstant.resourceSearch.EPIN,
            "headerTooltip": localConstant.resourceSearch.EPIN,
            "field": "ePin",
            "filter": "agTextColumnFilter",
            "tooltipField": "ePin",
            "width": 200,
        },
        {
            "headerName": localConstant.gridHeader.HARD_STAMP,
            "headerTooltip": localConstant.gridHeader.HARD_STAMP,
            "field": "hardStamp",
            "filter": "agTextColumnFilter",
            "tooltipField": "hardStamp",
            "width": 200,
        },
        {
            "headerName": localConstant.gridHeader.SOFT_STAMP,
            "headerTooltip": localConstant.gridHeader.SOFT_STAMP,
            "field": "softStamp",
            "filter": "agTextColumnFilter",
            "tooltipField": "softStamp",
            "width": 200,
        },
        {
            "headerName": localConstant.techSpec.techSpecSearch.PROFILE_STATUS,
            "headerTooltip": localConstant.techSpec.techSpecSearch.PROFILE_STATUS,
            "field": "profileStatus",
            "filter": "agTextColumnFilter",
            "tooltipField": "profileStatus",
            "width": 200,
        },
        {
            "headerName": localConstant.gridHeader.EMPLOYMENT_TYPE,
            "headerTooltip": localConstant.gridHeader.EMPLOYMENT_TYPE,
            "field": "employmentStatus",
            "filter": "agTextColumnFilter",
            "tooltipField": "employmentStatus",
            "width": 200,
        },
        {
            "headerName": localConstant.gridHeader.CITY,
            "headerTooltip": localConstant.gridHeader.CITY,
            "field": "city",
            "filter": "agTextColumnFilter",
            "tooltipField": "city",
            "width": 200,
        },
        {
            "headerName": localConstant.gridHeader.STATE,
            "headerTooltip": localConstant.gridHeader.STATE,
            "field": "county",
            "filter": "agTextColumnFilter",
            "tooltipField": "county",
            "width": 200,
        },
        {
            "headerName": localConstant.gridHeader.COUNTRY,
            "headerTooltip": localConstant.gridHeader.COUNTRY,
            "field": "country",
            "filter": "agTextColumnFilter",
            "tooltipField": "country",
            "width": 200,
        },
        {
            "headerName": localConstant.gridHeader.RAMP,
            "headerTooltip": localConstant.gridHeader.RAMP,
            "field": "ramp",
            "filter": "agTextColumnFilter",
            "tooltipField": "ramp",
            "width": 200,
        },
        {
            "headerName": localConstant.gridHeader.EREPORTING,
            "headerTooltip": localConstant.gridHeader.EREPORTING,
            "field": "eReporting",
            "filter": "agTextColumnFilter",
            "tooltipField": "eReporting",
            "width": 200,
        },
        {
            "headerName": localConstant.gridHeader.CATEGORY,
            "headerTooltip": localConstant.gridHeader.CATEGORY,
            "field": "category",
            "filter": "agTextColumnFilter",
            "tooltipField": "category",
            "width": 200,
        },
        {
            "headerName": localConstant.gridHeader.SUB_CATEGORY,
            "headerTooltip": localConstant.gridHeader.SUB_CATEGORY,
            "field": "subCategory",
            "filter": "agTextColumnFilter",
            "tooltipField": "subCategory",
            "width": 200,
        },
        {
            "headerName": localConstant.techSpec.gridHeaderConstants.SERVICES,
            "headerTooltip": localConstant.techSpec.gridHeaderConstants.SERVICES,
            "field": "service",
            "filter": "agTextColumnFilter",
            "tooltipField": "service",
            "width": 200,
        },
        {
            "headerName":localConstant.gridHeader.APPROVAL_STATUS,
            "headerTooltip": localConstant.gridHeader.APPROVAL_STATUS,
            "field": "approvalStatus",
            "filter": "agTextColumnFilter",
            "tooltipField": "approvalStatus",
            "width": 200,
        },
    ],

    "enableFilter": true,
    "enableSorting": true,
    "pagination": true,
    "gridTitlePanel": true,
    "clearFilter": true,
    "gridActions": true,
    "exportFileName": "Taxonomy Report",
    "customHeader": "Taxonomy Report",
    "gridHeight": 25,
};
