export const modalTitleConstant = {
    ASSIGNMENT_REFERENCE_DELETE_TITLE: 'Assignment Reference Delete Confirmation',
    ACCOUNT_REFERENCE_DELETE_TITLE: 'Account Reference Delete Confirmation',
    CONFIRMATION: 'Confirmation!',
    ALERT_WARNING: 'Warning Alert!!',
    REASON_FOR_REJECTION:'Reason For Rejection',
    ALLOCATED_VISIT_TIMESHEET:"Allocated Visit(s)/Timesheet(s)"
};

export const modalMessageConstant = {
    CONFIRMATION_SESSION:'Your session is about to expire in one minute, unless you continue working. Do you wish to extend your session?',
    ASSIGNMENT_REFERENCE_DELETE_MESSAGE: 'Are you sure you want to delete selected Assignment Reference?',
    ACCOUNT_REFERENCE_DELETE_MESSAGE: 'Are you sure you want to delete selected Accounts Reference?',
    ADDRESS_DELETE_MESSAGE: 'Are you sure you want to delete selected Address?',
    CONTACT_DELETE_MESSAGE: 'Are you sure you want to delete selected Contact?',
    DOCUMENT_DELETE_MESSAGE: 'Are you sure you want to delete selected Document?',
    DOCUMENT_NOT_DELETE_MESSAGE: 'One or more documents you have selected have been archived and cannot be deleted',
    OFFICE_DELETE_MESSAGE: 'Are you sure you want to delete selected Company Office?',
    INOVICE_REMITTANCE_MESSAGE: 'Are you sure you want to delete selected Invoice Remittance Text?',
    INVOICE_REMITTANCE_DEFAULT_MESSAGE: "You are trying to delete the Default Invoice Remittance. There must be an Invoice Remittance with the 'Default' set to 'Yes'.",
    INOVICE_FOOTER_MESSAGE: 'Are you sure you want to delete selected Invoice Footer Text?',
    INVOICE_FOOTER_DEFAULT_MESSAGE: "You are trying to delete the Default Invoice Footer. There must be an Invoice Footer with the 'Default' set to 'Yes'.",
    INVOICE_DEFAULT_CHECK_MESSAGE: 'The Default Footer has been already set up, do you want to override it?',
    INVOICE_REMITTANCE_CHECK_MESSAGE: 'The Default Invoice Remittance has been already set up, do you want to override it?',
    CUSTOMER_CANCEL_MESSAGE: 'Customer data got changed. Are you sure you want to cancel the changes?',
    COMPANY_CANCEL_MESSAGE: 'Company data got changed. Are you sure you want to cancel the changes?',
    REFRESH_MESSAGE: 'You may have unsaved changes! If you leave, your changes will be lost. Are you sure you want to continue?',
    DIVISION_COST_CENTRE_MESSAGE: 'Are you sure you want to delete selected Cost Centre?',
    DIVISION_MESSAGE: 'Are you sure you want to delete selected Company Division?',
    PAYROLL_MESSAGE: 'Are you sure you want to delete selected Company Payroll?',
    PAYROLL_PERIOD_NAME_MESSAGE: 'Are you sure you want to delete selected Payroll Period Name?',
    COMPANY_TAXES_MESSAGE: 'Are you sure you want to delete selected Company Tax?',
    FIXED_EXCHANGE_RATE_MESSAGE: 'Are you sure you want to delete selected Fixed Exchange Rate?',
    COMPANY_EXPECTED_MARGIN_DELETE_MESSAGE: "Are you sure you want to delete selected Company Expected Margin?",
    EMAIL_TEMPLATE_TEXT_LIMIT: "Maximun text length reached....",
    DOCUMENT_APPROVAL_DELETE_MESSAGE: "Are you sure you want to reject Document?",
    INVOICE_DEFAULT_MESSAGE: 'Are you sure you want to delete selected Invoice Reference(s)?',
    ATTACHMENT_TYPE_MESSAGE: 'WARNING – deleting an attachment type will stop these documents flowing through to Invoicing -including existing drafted & committed invoices. Do you want to continue ?',  //Changes For ITK D-1118 
    REVENUE_DELETE_MESSAGE: 'Are you sure you want to delete selected Revenue(s)?',
    COST_DELETE_MESSAGE: 'Are you sure you want to delete selected Cost(s)?',
    /*AddScheduletoRF*/
    ADD_SCHEDULE_TO_RF:'All Schedules and associated rates will be copied down to all Is Related Contracts. Do you want to Continue?',
    contract: {
        rateSchedule: {
            RATE_SCHEDULE_MESSAGE: 'Are you sure you want to delete selected Charge Schedule(s)?',
            CHARGE_TYPE_MESSAGE: 'Are you sure you want to delete selected Charge Type?',
        },
        CONTRACT_CANCEL_MESSAGE: 'Contract data got changed. Are you sure you want to cancel the changes?',
        CONTRACT_DELETE_MESSAGE: 'Deleting this Contract will delete all documents linked to the contract. Do you wish to continue with the deletion?',
        CHARGE_RATES_OVERLAP: 'There are one or more Charge Types that overlap.',
        SCHEDULE_SHOULD_HAVE_ATLEAST_ONE_CHARGE_RATE: 'Below listed Schedules should have at least One Charge Rate',
    },
      /** Supplier Modal Message - Starts */
      SUPPLIER_CONTACT_MESSAGE:'Are you sure you want to delete Supplier Contact(s)?',
      SUPPLIER_CANCEL_MESSAGE:'Are you sure you want to cancel the Supplier changes?',
      SUPPLIER_DELETE_MESSAGE:'Deleting this Supplier will delete all documents linked to the supplier. Do you wish to continue with the deletion?',
      /** Supplier Modal Message - Ends */

    //Added For Assignment
    assignment:{
        additionalExpenses:{
            ADDITIONAL_EXPENSES_MESSAGE:'Are you sure you want to delete the selected Additional Expense(s)?',
        },
        //Supplier Information Tab
        supplierInformation:{
            UNASSIGNED_SUB_SUPPLIER: 'Please note that Sub-Suppliers cannot be de-selected once Resources have been assigned to them.Please unassign the Resources and save first.',
            CANNOT_REMOVE_PART_OF_ASSIGNMENT: 'Cannot Remove Part of Assignment since the Sub-Supplier is assigned to Visit(s)',
        },
        //Supplier Information Tab
    },
    ASSIGNMENT_STATUS_COMPLETE_VISITS:'Mark the assignment as complete and delete all associated itinerary records?',
    ASSIGNMENT_STATUS_COMPLETE_VISIT1:'The Complete flag can not be set because there has not been a final visit.',
    ASSIGNMENT_COMPLETE_VAL_ON_FINAL_VISIT:'This assignment cannot be unmarked as it contains a final visit; instead unmark the visit as final',
    ASSIGNMENT_CC_APPLY_PERCENT:'Do you wish to copy the Percentages to the Inter Company Discounts on the assignment?',
    ASSIGNMENT_CC_APPLY_UPDATE_PERCENT:'The Percentages on the Assignment do not match the Percentages on the Calculator. Do you wish to update the values on the Calculator?',
    ASSIGNMENT_CC_KEEP_CHANGES:'Do you wish to keep the changes to calculator?',
    ASSIGNMENT_COPY_CONFIRM:'You have unsaved changes, Are you sure you want to Copy Assignment?',
    OM_REJECTED_RESOURCE: 'Resource already rejected by OM. Do you want to continue?',
    RECORD_TO_DELETE_CONFIRM: 'After downloading, Do you want the File to be deleted from server?',
    COPY_CONFIRMATION: 'Do you want to copy all the details from the selected Parent Contract?',
    COPY_FRAMEWORK_CONFIRMATION:'Do you want to copy all the details from the selected Framework Contract?',
    CUSTOMER_ADDRESS_CONFIRMATION: 'A Customer must posses at least one address and contact before a contract can be created',
    PAY_RATE_SCHEDULE: 'Are you sure you want to delete selected Payrate Schedule?',
    PAY_RATE_DETAIL: 'Are you sure you want to delete selected Payrate details?',
    INTERNAL_TRAINING_DETAIL: 'Are you sure you want to delete selected Internal Training details?',
    COMPETENCY_DETAIL: 'Are you sure you want to delete selected Competency details?',
    CUSTOMER_APPROVED_DETAIL: 'Are you sure you want to delete selected Customer Approved details?',
    RESOURCE_STATUS_DELETE_MESSAGE: 'Are you sure you want to delete selected Stamp details?',
    SENSITIVE_DOCUMENTS_DELETE_MESSAGE: 'Are you sure you want to delete selected Sensitive Document?',
    RESOURCE_CAPABILITY_DELETE_MESSAGE: 'Are you sure you want to delete selected details?',
    TAXONOMY_APPROVAL_DELETE_MESSAGE: 'Are you sure you want to delete selected details',
    EDUCATIONAL_DETAILS: 'Are you sure you want to delete  selected Educational Summary details?',
    PROFESSIONAL_SUMMARY: 'Are you sure you want to delete selected Professional Summary details?',
    PROJECT_CANCEL_MESSAGE: 'Project data got changed. Are you sure you want to cancel the changes?',
    CLIENT_NOTIFICATION_DELETE: 'Are you sure you want to delete selected Client Notification?',
    CLASSIFICATION_MESSAGE: 'Are you sure you want to delete the selected Classification?',
    RATE_SCHEDULE_MAESSAGE: 'Are you sure you want to delete the selected Rate Schedule?',
    ASSIGNMENT_REFERENCE_MESSAGE: 'Are you sure you want to delete the selected Assignment Reference?',
    TECHNICAL_SPEC_CANCEL_MESSAGE: 'Resource data got changed. Are you sure you want to cancel the changes?',
    PROJECT_DELETE_MESSAGE: 'Deleting this Project will delete all document linked to the Project. Do you wish to continue with deletion?',
    ASSIGNMENT_DELETE_MESSAGE: 'Are you sure you want to delete this Assignment? \n Any associated itineraries will be deleted.',
    TECHSPEC_DRAFT_DELETE_MESSAGE: 'Deleting this technical specialist draft will delete all the infomation to the draft. Do you wish to continue with deletion?',
    OP_ASSIGNMENT_DELETE_MESSAGE: 'Sorry but this assignment belongs to a different company - unable to delete.',
    CANCEL_CHANGES: 'This form has changes that have not been saved to the database. Continue with cancelling the changes? (Note: clicking yes will result in data loss)',
    //CANCEL_CHANGES:'Resource data got changed. Are you sure you want to cancel the changes?',
    CHANGING_OPERATING_COMPANY: 'Changing the Operating Company will neccessitate the clearing of the following data: \n {0} \n Do you still wish to change the Operating Company?',
    TECH_SPEC_SCHEDULE_DELETE_MESSAGE:'Are you sure you want to delete the selected Resource Schedule?',
    TECH_SPEC_DELETE_MESSAGE:'Are you sure you want to remove this Resource from this assignment? \n Any associated itineraries will be deleted',
    TECH_SPEC_ASSOCIATED_DELETE_MESSAGE:'This Resource is associated with Main-Supplier/Sub-Supplier on this Assignment. Please first delete these associations and save the changes.\nPlease note override resources cannot be deleted.',
    TECH_SPEC_ASSOCIATED_DELETE_MESSAGE_VISITORTIMESHEET:'This resource cannot be deleted from this Assignment as he/she is associated with one or more Visits or Timesheets',
    TECH_SPEC_ADD_MESSAGE:"Please ensure any new Resources are assigned Sub-Suppliers to Visit on the 'Supplier Information' tab",
    SUPPLIER_PO_CHANGE_MESSAGE:"Warning: changing the Purchase Order will remove the associated Sub-Suppliers on this Assignment and any Assigned Specialists. Click 'Yes' to delete these records or 'No' to keep using the old Purchase Order.",
    SUPPLIER_PO_CONTACT_MESSAGE:'Are you sure you want delete selected Sub-Supplier?',
    SUPPLIER_PO_DELETE_MESSAGE: 'Deleting this Supplier PO will delete all documents linked to the Purchase Order. Do you wish to continue with the deletion?',
    SUPPLIER_PO_CANCEL_MESSAGE: 'SupplierPO data got change. Are you sure you want to cancel the changes?',
    CREATE_ROLE_CANCEL_MESSAGE: 'Role data got changed. Are you sure you want to cancel the changes?',
    CREATE_USER_CANCEL_MESSAGE: 'User data got changed. Are you sure you want to cancel the changes?',
    ROLE_DELETE_MESSAGE: 'Are you sure you want to delete selected Role Details?',
    USER_DELETE_MESSAGE: 'Are you sure you want to delete selected User Details?',
    VISIT_REFERENCE_MESSAGE: 'Are you sure you want to delete the Selected Visit Reference?',
    VISIT_SUPPLIER_PERFORMANCE: 'Are you sure you want to delete the Selected Supplier Performance?',
    DELETE_VISIT_TECH_SPEC: 'Are you sure you want to delete the selected row(s)?',
    DELETE_TECH_SPEC_ITEM_ERROR: 'Item cannot be deleted as charge data has been entered',
    DELETE_PAY_TECH_SPEC_ITEM_ERROR: 'Item cannot be deleted as pay data has been entered',
    DELETE_INVOICED_TECH_SPEC_ITEM_ERROR: 'Item cannot be deleted as data has been passed to Invoicing or Payroll',
    TECH_SPEC_DELETE_ON_ARS_DESELECT: 'Please delete the deselected ARS resource from Assigned Resources Tab',
    /** pre-assignment modal constant - starts*/
    SUB_SUPPLIER_DELETE_MESSAGE:'Are you sure you want to delete selected Sub-Supplier?',
    SUPPLIER_DUPPLICATE_MESSAGE:'Supplier(s) with a similar name already exists: \r\n {0} \r\n Do you wish to continue?',
    /** pre-assignment modal constant - ends*/
    NOT_APPEAR_ON_CV: 'By ticking this box you are confirming that this Assignment will not appear on the Standard Intertek CV',
    APPEAR_ON_CV: 'By unticking this box you are confirming that this Assignment will now appear on the Standard Intertek CV',
    /**Timesheet Modal Constabts - START */
    TIMESHEET_DELETE_MESSAGE: 'Deleting this timesheet will delete all document linked to the timesheet. Do you wish to continue with deletion?',
    TIMESHEET_REFERENCE_MESSAGE: 'Are your sure you want to delete the Selected Timesheet Reference?',
    REJECT_REASON_MESSAGE:'Please enter the reason why you are rejecting this Visit/Timesheet in the box below.',
    VISIT_TIMESHEET_REPORT_WARNING_MESSAGE: 'This form has changes that have not been saved to the database. \n Reports use the data saved to the database and may not match what is currently on screen. \n\n Do you wish to continue creating the report?',
    ZERO_CHARGE_RATE_OR_UNITS:"Some expenses on  this Timesheet  have either a 'Charge Rate' or 'Charge Unit' value of 0. \r Continue Save?",
    ZERO_CHARGE_RATE_OR_UNITS_VISIT:"Some expenses on this Visit have either a 'Charge Rate' or 'Charge Unit' value of 0. \r Continue Save?",
    NO_TIMESHEET_ENTRIES_FOR_TECHSPEC:'Resource records exist that have not had timesheet entries recorded for them:\r\n {0} \r\n Are you sure you wish to save?',
    TIMESHEET_APPROVE_CONFIRM_OC:'Are you sure you want to approve the timesheet? \r Further changes can only be done with permission of the contract holding company.',
    TIMESHEET_APPROVE_CONFIRM_CHC:'Are you sure you want to approve the timesheet? \r Further changes will not be possible once approved.',
    TIMESHEET_DELETE_LINEITEM_MESSAGE: 'Are your sure you want to delete the LineItem?',
    TIMESHEET_SAVE_CONFIRM:'The current record has changes that have not been saved. Before changing the status you must save any unsaved changes. \r\n Yes = Save changes and then change the status \r\n No = Do not save changes and cancel  change of status \r\n Continue Saving?',
    TIMESHEET_ADD_UNLINKED_EXPENSES:'The following are currently listed  under Additional Expenses for this assignment. \r\n Select rows and click OK to add them to this Account.',
    TIMESHEET_ASSIGNMENT_DATE_VALIDATION:'This Assignment already contains a Timesheet with this Timesheet date. Do you wish to continue?',
    TS_WITH_MULTIPLE_VISIT_TIMESHEET_ON_APPROVE:'{0} is already associated with the following Visit(s)/Timesheet(s) on the visit date - {1}',
    TIMESHEET_INVALID_CALENDAR_DATA_VALIDATION: 'The Timesheet already has Calendar entries for older dates.  Do you want to remove ALL of them? ?',
    TIMESHEET_DELETE_HANDLER_WARNING:'The following problem occurred while saving changes: \r\n\n The Timesheet contains Specialist Account items which have been transferred to invoicing and therefore cannot be deleted.',
    TIMESHEET_DELETE_HANDLER_WARNING_FOR_PAY:'The following problem occurred while saving changes: \r\n\n The Timesheet contains Specialist Account items which have been transferred to payroll and therefore cannot be deleted.',
    // TS_WITH_OTHER_VISIT_TIMESHEET_ON_APPROVE:'{0} is already associated with the following Visit(s)/Timesheet(s) on the visit date - {1}',
    /**Timesheet Modal Constabts - END */

    /**Visit Modal Constabts - START */
    VISIT_DELETE_MESSAGE: 'Deleting this visit will delete all document linked to the visit. Do you wish to continue with deletion?',        
    NO_VISIT_ENTRIES_FOR_TECHSPEC:'Resource records exist that have not had visit entries recorded for them: {0} \r Are you sure you wish to save?',
    VISIT_SAVE_CONFIRM:'The current record has changes that have not been saved. Before changing the status you must save any unsaved changes. \r\n Yes = Save changes and then change the status \r\n No = Do not save changes and cancel  change of status \r\n Continue Saving?',
    VISIT_APPROVE_CONFIRM_OC:'Are you sure you want to approve the visit? \r Further changes can only be done with permission of the contract holding company.',
    VISIT_APPROVE_CONFIRM_CHC:'Are you sure you want to approve the visit? \r Further changes will not be possible once approved.',
    VISIT_FINAL_VISIT_SAVE: 'Saving a Final Visit - do you wish to mark the Assignment as complete and delete all associated itinerary records? \r\n Select Yes to proceed.',
    VISIT_ASSIGNMENT_DATE_VALIDATION: 'This Assignment already contains a Visit with this Visit date. Do you wish to continue?',
    VISIT_INVALID_CALENDAR_DATA_VALIDATION: 'The Visit already has Calendar entries for older dates.  Do you want to remove ALL of them?',
    VISIT_DELETE_HANDLER_WARNING:'The following problem occurred while saving changes: \r\n\n The Visit contains Specialist Account items which have been transferred to invoicing and therefore cannot be deleted.',
    VISIT_DELETE_HANDLER_WARNING_FOR_PAY:'The following problem occurred while saving changes: \r\n\n The Visit contains Specialist Account items which have been transferred to payroll and therefore cannot be deleted.',
    /**Visit Modal Constabts - END */
    /** admin */
    ASSIGMENT_COMPLETE_STATUS:'You cannot delete Complete or In Progress Status?',

    /** Admin-Starts */
    REFERENCE_TYPE:'Are you sure you want to delete Assignment ReferenceType(s)?',
    ASSIGMENT_LIFECYCLE:'Are you sure you want to delete Assignment Lifecycle(s)?',
    ASSIGMENT_STATUS:'Are you sure you want to delete Assignment Status(s)?',  
    /**Admin -Ends */

    REASSIGN_MY_TASK: 'Are you sure you want to reassign the event?',
};